/**
* @version		$Id: fckeditor.php 1154 18-1-2008 AW
* @package		JoomlaFCK
* @copyright	Copyright (C) 2006 - 2008 WebXSolution Ltd. All rights reserved.
* @license		Creative Commons Licence
* The code for this additional work for the FCKeditor has been  been written/modified by WebxSolution Ltd.
* You may not copy or distribute the work without written consent
* from WebxSolution Ltd.
*/
﻿ var FCKXml = function(){try{this.xmlHttpGetSuggestions = new XMLHttpRequest();} catch(e){}; try{this.xmlHttpGetSuggestions = new ActiveXObject( 'Msxml2.XMLHTTP' ) ;} catch(e){}; try{this.xmlHttpGetSuggestions = new ActiveXObject( 'Microsoft.XMLHTTP' ) ;} catch(e){}};FCKXml.prototype.LoadUrl = function( urlToCall,asyncFunctionPointer ){var oFCKXml = this; var bAsync = ( typeof(asyncFunctionPointer) == 'function' ); this.xmlHttpGetSuggestions.open( "GET",urlToCall,bAsync ); if(oFCKXml.xmlHttpGetSuggestions){if ( bAsync ){this.xmlHttpGetSuggestions.onreadystatechange = function(){if ( oFCKXml.xmlHttpGetSuggestions.readyState == 4 ){if ( ( oFCKXml.xmlHttpGetSuggestions.status != 200 && oFCKXml.xmlHttpGetSuggestions.status != 304 ) || oFCKXml.xmlHttpGetSuggestions.responseXML == null || oFCKXml.xmlHttpGetSuggestions.responseXML.firstChild == null ){throw ( 'The server didn\'t send back a proper XML response. Please contact your system administrator.\n\n' +'XML request error: ' + oFCKXml.xmlHttpGetSuggestions.statusText + ' (' + oFCKXml.xmlHttpGetSuggestions.status + ')\n\n' +'Requested URL:\n' + urlToCall + '\n\n' +'Response text:\n' + oFCKXml.xmlHttpGetSuggestions.responseText ) ;};oFCKXml.DOMDocument = oFCKXml.xmlHttpGetSuggestions.responseXML;asyncFunctionPointer( oFCKXml ) ;}}};oFCKXml.xmlHttpGetSuggestions.send( null ); if ( ! bAsync ){if ( oFCKXml.xmlHttpGetSuggestions.status == 200 || oFCKXml.xmlHttpGetSuggestions.status == 304 )oFCKXml.DOMDocument = oFCKXml.xmlHttpGetSuggestions.responseXML; else{throw ( 'XML request error: ' + oFCKXml.xmlHttpGetSuggestions.statusText + ' (' + oFCKXml.xmlHttpGetSuggestions.status + ')' ) ;}}}};FCKXml.prototype.ToArray =  function(tagName){var resultsXml  = this.DOMDocument.getElementsByTagName(tagName); var resultsArray= new Array(); for(i=0;i<resultsXml.length;i++)resultsArray[i]=resultsXml.item(i).firstChild.data; return resultsArray;};